---
- name: Configure Database server
  hosts: db01

  user: vagrant
  become: true
  
  vars_files:
    - vars/main.yml
  
  vars:
    dbname: "db01"
    dbusername: "root"
    dbpassword: "db01password"
  
  tasks:
    - name: Configure hosts (lab)
      lineinfile: line "{{item}}" path=/etc/hosts
      with_items: 
        - 192.168.2.10 control-node
        - 192.168.2.11 app01
        - 192.168.2.12 db01

  roles:
    - default-os-config
    - role: geerlingguy.mysql

