---
- name: Configure Database server
  hosts: db01

  user: vagrant
  become: true
  
  vars_files:
    - vars/main.yml
  
  vars:
    dbname: "db01"
    dbusername: "root"
    dbpassword: "db01password"

  roles:
    - default-os-config
    - role: geerlingguy.mysql

