- name: Upgrade OS packages
  yum:
    name: '*'
    state: latest

- name: Configure hosts (lab)
  lineinfile: 
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items: 
    - 192.168.2.10 control-node
    - 192.168.2.11 app01
    - 192.168.2.12 db01

- name: Git client installation
  yum:
    name: git
    state: latest