mysql_root_password: db01password

mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
    
mysql_users:
  - name: notesapp
    host: "%"
    password: notesapppassword
    priv: "notes.*:ALL"