# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.2.11"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
